/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoClienteRouteImport } from './routes/acesso-cliente'
import { Route as BrandStudioRouteImport } from './routes/brand-studio'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComunicacaoRouteImport } from './routes/comunicacao'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as PassaporteRouteImport } from './routes/passaporte'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ProximoCapituloRouteImport } from './routes/proximo-capitulo'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as RadarIndexRouteImport } from './routes/radar.index'
import { Route as RadarClienteIdRouteImport } from './routes/radar.$clienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoClienteRoute = AcessoClienteRouteImport.update({
  id: '/acesso-cliente',
  path: '/acesso-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandStudioRoute = BrandStudioRouteImport.update({
  id: '/brand-studio',
  path: '/brand-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacaoRoute = ComunicacaoRouteImport.update({
  id: '/comunicacao',
  path: '/comunicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const PassaporteRoute = PassaporteRouteImport.update({
  id: '/passaporte',
  path: '/passaporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximoCapituloRoute = ProximoCapituloRouteImport.update({
  id: '/proximo-capitulo',
  path: '/proximo-capitulo',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarIndexRoute = RadarIndexRouteImport.update({
  id: '/radar/',
  path: '/radar/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarClienteIdRoute = RadarClienteIdRouteImport.update({
  id: '/radar/$clienteId',
  path: '/radar/$clienteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-cliente': typeof AcessoClienteRoute
  '/brand-studio': typeof BrandStudioRoute
  '/clientes': typeof ClientesRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/inicio': typeof InicioRoute
  '/passaporte': typeof PassaporteRoute
  '/perfil': typeof PerfilRoute
  '/proximo-capitulo': typeof ProximoCapituloRoute
  '/registrar': typeof RegistrarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/radar/$clienteId': typeof RadarClienteIdRoute
  '/radar/': typeof RadarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-cliente': typeof AcessoClienteRoute
  '/brand-studio': typeof BrandStudioRoute
  '/clientes': typeof ClientesRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/inicio': typeof InicioRoute
  '/passaporte': typeof PassaporteRoute
  '/perfil': typeof PerfilRoute
  '/proximo-capitulo': typeof ProximoCapituloRoute
  '/registrar': typeof RegistrarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/radar/$clienteId': typeof RadarClienteIdRoute
  '/radar': typeof RadarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-cliente': typeof AcessoClienteRoute
  '/brand-studio': typeof BrandStudioRoute
  '/clientes': typeof ClientesRoute
  '/comunicacao': typeof ComunicacaoRoute
  '/inicio': typeof InicioRoute
  '/passaporte': typeof PassaporteRoute
  '/perfil': typeof PerfilRoute
  '/proximo-capitulo': typeof ProximoCapituloRoute
  '/registrar': typeof RegistrarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/radar/$clienteId': typeof RadarClienteIdRoute
  '/radar/': typeof RadarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-cliente'
    | '/brand-studio'
    | '/clientes'
    | '/comunicacao'
    | '/inicio'
    | '/passaporte'
    | '/perfil'
    | '/proximo-capitulo'
    | '/registrar'
    | '/auth/callback'
    | '/radar/$clienteId'
    | '/radar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-cliente'
    | '/brand-studio'
    | '/clientes'
    | '/comunicacao'
    | '/inicio'
    | '/passaporte'
    | '/perfil'
    | '/proximo-capitulo'
    | '/registrar'
    | '/auth/callback'
    | '/radar/$clienteId'
    | '/radar'
  id:
    | '__root__'
    | '/'
    | '/acesso-cliente'
    | '/brand-studio'
    | '/clientes'
    | '/comunicacao'
    | '/inicio'
    | '/passaporte'
    | '/perfil'
    | '/proximo-capitulo'
    | '/registrar'
    | '/auth/callback'
    | '/radar/$clienteId'
    | '/radar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoClienteRoute: typeof AcessoClienteRoute
  BrandStudioRoute: typeof BrandStudioRoute
  ClientesRoute: typeof ClientesRoute
  ComunicacaoRoute: typeof ComunicacaoRoute
  InicioRoute: typeof InicioRoute
  PassaporteRoute: typeof PassaporteRoute
  PerfilRoute: typeof PerfilRoute
  ProximoCapituloRoute: typeof ProximoCapituloRoute
  RegistrarRoute: typeof RegistrarRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RadarClienteIdRoute: typeof RadarClienteIdRoute
  RadarIndexRoute: typeof RadarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-cliente': {
      id: '/acesso-cliente'
      path: '/acesso-cliente'
      fullPath: '/acesso-cliente'
      preLoaderRoute: typeof AcessoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-studio': {
      id: '/brand-studio'
      path: '/brand-studio'
      fullPath: '/brand-studio'
      preLoaderRoute: typeof BrandStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacao': {
      id: '/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof ComunicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passaporte': {
      id: '/passaporte'
      path: '/passaporte'
      fullPath: '/passaporte'
      preLoaderRoute: typeof PassaporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximo-capitulo': {
      id: '/proximo-capitulo'
      path: '/proximo-capitulo'
      fullPath: '/proximo-capitulo'
      preLoaderRoute: typeof ProximoCapituloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/': {
      id: '/radar/'
      path: '/radar'
      fullPath: '/radar/'
      preLoaderRoute: typeof RadarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/$clienteId': {
      id: '/radar/$clienteId'
      path: '/radar/$clienteId'
      fullPath: '/radar/$clienteId'
      preLoaderRoute: typeof RadarClienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoClienteRoute: AcessoClienteRoute,
  BrandStudioRoute: BrandStudioRoute,
  ClientesRoute: ClientesRoute,
  ComunicacaoRoute: ComunicacaoRoute,
  InicioRoute: InicioRoute,
  PassaporteRoute: PassaporteRoute,
  PerfilRoute: PerfilRoute,
  ProximoCapituloRoute: ProximoCapituloRoute,
  RegistrarRoute: RegistrarRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RadarClienteIdRoute: RadarClienteIdRoute,
  RadarIndexRoute: RadarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
